In [1]:
import torch
import numpy as np
import os

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
basic_tensor = tensor = torch.tensor([[1,2,3],[11,22,33]])
basic_tensor, basic_tensor.dtype

(tensor([[ 1,  2,  3],
         [11, 22, 33]]),
 torch.int64)

In [1]:
basic_tensor.device

NameError: name 'basic_tensor' is not defined

In [ ]:
basic_tensor.shape

torch.Size([2, 3])

In [ ]:
basic_tensor.requires_grad

False

In [ ]:
tensor = tensor = torch.tensor([[1,2,3],[11,22,33]],
                              dtype=torch.float,
                              device=device,
                              requires_grad = True)
tensor, tensor.dtype

(tensor([[ 1.,  2.,  3.],
         [11., 22., 33.]], device='cuda:0', requires_grad=True),
 torch.float32)

In [ ]:
tensor.device


device(type='cuda', index=0)

In [ ]:
tensor.requires_grad

True

### Other commonly used tensors

In [ ]:
x= torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x= torch.zeros(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x= torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x= torch.rand(size=(3,3))
x

tensor([[0.0817, 0.0192, 0.9470],
        [0.7987, 0.0400, 0.5852],
        [0.0995, 0.7040, 0.3780]])

In [ ]:
x = torch.eye(3) #gives identity matrix since they are always square
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
x = torch.arange(start = 0, end =7, step = 3)
x

tensor([0, 3, 6])

In [ ]:
x = torch.linspace(start = 0, end =7, steps = 3)
x

tensor([0.0000, 3.5000, 7.0000])

In [ ]:
x= torch.rand(size= (3,4)).normal_(mean=0,std = 1) #normalization
x

tensor([[ 0.8255, -0.6276,  1.2804,  0.2244],
        [-1.6197,  1.0302,  0.6541, -0.1424],
        [ 0.3235,  0.4318,  0.2971,  0.9224]])

In [ ]:
x = torch.rand(size=(3,4)).uniform_(3,6) #uniform matrix
x

tensor([[4.9825, 4.8392, 3.8939, 3.7154],
        [5.1256, 5.8051, 4.3470, 3.7813],
        [5.4220, 4.1507, 5.7455, 5.1357]])

In [ ]:
x = torch.diag(torch.ones(10)) #diagonal matrix
x, x.shape

(tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]),
 torch.Size([10, 10]))

In [ ]:
x = torch.diag(5*torch.ones(10))
x, x.shape

(tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]]),
 torch.Size([10, 10]))

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
x.bool()

tensor([False,  True,  True,  True])

In [ ]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [ ]:
x.short() #int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [ ]:
x.long(), x.dtype #int64

(tensor([0, 1, 2, 3]), torch.int64)

In [ ]:
x.half() #float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [ ]:
x.float(), x.dtype #float32 !caution

(tensor([0., 1., 2., 3.]), torch.int64)

In [ ]:
x.double() #float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [ ]:
np_array = np.array([[1,2,3],[1,2,3]])
np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [ ]:
tensor.numpy(),tensor.dtype

(array([[1, 2, 3],
        [1, 2, 3]]),
 torch.int32)